language: java
jdk:
  - oraclejdk8
 
before_install:
 - chmod +x gradlew
 - git fetch --unshallow
 - git fetch origin testbranch:testbranch

after_success:
- ./gradlew jacocoTestReport

after_failure:
- cat build/test-results/*.xml
